language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: OZXeUKqEP25BLiC6j6OyQ+Yi9J3etX/+HsreQziENOOKD0SFtiIFrnH7f83tkpFNG9okYi5SR2Frrh0Xe1MU5z4MTUMxg3Qk3xEvYDxLCmOFXGE9Mmv5PqMQ1zx63lT+xn/Bin4WYgBYJDnOxuVVe53ePmzoiEVC+HJ3+1dB2eU=
